spring:
    datasource:
        name: test
        url: jdbc:mysql://118.190.74.13:3306/doge?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: meddkim
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
#    thymeleaf:
#      prefix: classpath:/templates/
#      mode: LEGACYHTML5

#jfinal:
#    modelBasePath: com.doge.blog.entity

server:
  port: 8015
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.doge.blog.domain
  config-location: classpath:mybatis/mybatis-config.xml



