# 主数据源
spring:
    datasource:
      type: com.zaxxer.hikari.HikariDataSource  #com.zaxxer.hikari.0x7fffffff;
      name: HikariDataSource0
      url: jdbc:mysql://118.190.74.13:3306/doge?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: meddkim
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        leak-detection-threshold: 16000
        connection-timeout: 30000
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss # Date类型数据输出时的根式转换
      time-zone: GMT+8 # 指定时区
#    thymeleaf:
#      prefix: classpath:/templates/
#      mode: LEGACYHTML5

#jfinal:
#    modelBasePath: com.doge.blog.entity

server:
  port: 8015
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.doge.blog.domain
  config-location: classpath:mybatis/mybatis-config.xml


